### Elasticsearch ###

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: myelastic
spec:
  version: 8.12.1
  nodeSets:
  - name: master
    count: 2
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: nfs-csi #Change this to the desired storageclass for the storage
        resources:
          requests:
            storage: 10Gi
    config:
      node.roles: ["master"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 1
              memory: 2Gi

### Optional fix to remove warning ###

        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']

### End of Optional fix to remove warning ###

  - name: data
    count: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: nfs-csi #Change this to the desired storageclass for the storage
        resources:
          requests:
            storage: 10Gi
    config:
      node.roles: ["data", "ingest"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 1
              memory: 2Gi

### Optional fix to remove warning ###

        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']

### End of Optional fix to remove warning ###

  - name: datawarm
    count: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: nfs-csi #Change this to the desired storageclass for the storage
        resources:
          requests:
            storage: 10Gi
    config:
      node.roles: ["data", "data_warm"]
    podTemplate:
          spec:
            containers:
            - name: elasticsearch
              resources:
                limits:
                  cpu: 1
                  memory: 2Gi
                requests:
                  cpu: 1
                  memory: 2Gi

### Optional fix to remove warning ###

            initContainers:
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']

### End of Optional fix to remove warning ###

  http:
    service:
      spec:
        type: LoadBalancer
        ports: 
        - protocol: TCP
          port: 9200
          targetPort: 9200
          name: https
---
