### Kibana ###


apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: mykibana
spec:
  version: 8.12.1
  count: 1
  elasticsearchRef:
    name: myelastic
  config:
    xpack.fleet.agents.elasticsearch.hosts: ["https://myelastic-es-http.default.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://myfleet-agent-http.default.svc:8220"]
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system
  podTemplate:
    spec:
      priorityClassName: elastic-cluster-high-priority
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
          - name: SERVER_PUBLICBASEURL
            value: "https://kibana.homelab"
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 2Gi
  http:
    service:
      spec:
        type: LoadBalancer
        ports: 
        - protocol: TCP
          port: 5601
          targetPort: 5601
          name: https
---
